### ISSUE TITLE
building on windows - main.exe crashes

### ISSUE THREAD

**Issue by geslotencirkel** [janivanecky/iris#1]
first attempt with go and installed the latest windows version. Cloned Iris into the Go local path and it autodownloads required GL libraries and etc when invoking "go build main.go" . Just assuming this is the right way. The resulting main.exe crashes however.

`C:\Users\x>C:\Users\x\go\projects\iris\main.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4aac8d]

goroutine 1 [running, locked to thread]:
syscall.(*Proc).Addr(...)
        E:/Go/src/syscall/dll_windows.go:154
syscall.(*Proc).Call(0x0, 0x0, 0x0, 0x0, 0x860fe0, 0xc00008e000, 0x0, 0x10006)
        E:/Go/src/syscall/dll_windows.go:169 +0x6d
_/C_/Users/x/go/projects/iris/lib/platform.GetWindowScaling(0x0)
        C:/Users/x/go/projects/iris/lib/platform/platform.go:30 +0x8f
_/C_/Users/x/go/projects/iris/lib/platform.init.0()
        C:/Users/x/go/projects/iris/lib/platform/platform.go:20 +0x3c`

**Comment by janivanecky** [comment]
That's weird, it seems that your User32.dll doesn't contain GetDpiForSystem. As a quick fix you can just replace body of `GetWindowScaling` function inside `lib/platform/platform.go` so it returns your OS's scaling factor.

**Comment by geslotencirkel** [comment]
Couldn't really do it elegantly because not a golfer, so just removed calls to the function and then getting this error after building and running:

> 
C:\Users\x\go\projects\iris>main
panic: open trash.png: The system cannot find the file specified.

goroutine 1 [running, locked to thread]:
_/C_/Users/x/go/projects/iris/app.GetSettingsBar(0xc0009a4000, 0x100000, 0x10
0000, 0x400, 0x400, 0xc000076330, 0x4044000000000000, 0x0, 0x0, 0x0, ...)
        C:/Users/x/go/projects/iris/app/settings_bar.go:80 +0x363
main.main()
        C:/Users/x/go/projects/iris/main.go:193 +0xb23

**Comment by geslotencirkel** [comment]
OK got it working! made a png called trash.png and changed the format from nrgba to rgba in `settings_bar.go` since never heard of nrgba or how to make one. phew

**Comment by janivanecky** [comment]
Ah, sorry - I forgot to commit to image. I pushed a new update with the image.
